<?php

return array(
    'color_primary'      => '#3157d5',
    'color_secondary'    => '#6750a4',
    'color_link'         => '#2448bd',
    'color_background'   => '#f4f6fb',
    'color_surface'      => '#ffffff',
    'color_text'         => '#202431',
    'site_max_width'     => '1200px',
    'reading_width'      => '72ch',
    'font_family'        => 'humanist',
    'font_size'          => '16px',
    'spacing'            => 'normal',
    'radius'             => 'medium',
    'sidebar_position'   => 'right',
    'show_left_sidebar'  => false,
    'show_right_sidebar' => true,
    'button_style'       => 'solid',
    'menu_style'         => 'floating',
    'block_style'        => 'card',
    'header_style'       => 'gradient',
    'footer_style'       => 'dark',
    'color_scheme'       => 'light',
    'admin_ui_mode'      => 'modern',
    'admin_navigation_source' => 'both',
    'mobile_menu'        => true,
    'editor_hide_sidebars' => true,
    'share_facebook'     => false,
    'share_linkedin'     => false,
    'share_x'            => false,
    'adsense_enabled'    => false,
    'adsense_client'     => '',
    'topic_h1_enabled'   => false,
    'html_lang'          => 'auto',
    'sitemap_path'       => '',
    'logo'               => 'images/logo-mark.svg',
    'header_image'       => '',
);
